py_binary(
    name = "embedding_pca",
    srcs = ["embedding_pca.py"],
    deps = [
        "//tensorflow:tensorflow_py",
        "//tensorflow/Source/lm/rnn:rnn_pb_py",
        "//tensorflow/Source/lm:vocab_pb_py",
    ]
)
