input_tensor_name: "inference/rnn/inputs:0"
predictions_tensor_name: "inference/rnn/predictions:0"
h {
  initial: "inference/rnn/zeros:0"
  final: "inference/rnn/RNN/MultiRNNCell/Cell0/BasicRNNCell/Tanh:0"
}
