cc_library(
    name = "lm",
    srcs = ["lm.h"],
    visibility = [
        "//lm/ngram:__subpackages__",
        "//benchmark:__subpackages__"],
    deps = [],
)

# TODO: Change this to py_proto_library.
py_library(
    name = "vocab_pb2",
    srcs = ["vocab_pb2.py"],
    visibility = ["//visibility:public"],
    deps = [],
)
