# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vocab.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vocab.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0bvocab.proto\"D\n\x05Vocab\x12\x19\n\x04item\x18\x01 \x03(\x0b\x32\x0b.Vocab.Item\x1a \n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04word\x18\x02 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VOCAB_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Vocab.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Vocab.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='word', full_name='Vocab.Item.word', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=83,
)

_VOCAB = _descriptor.Descriptor(
  name='Vocab',
  full_name='Vocab',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='Vocab.item', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_VOCAB_ITEM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=83,
)

_VOCAB_ITEM.containing_type = _VOCAB
_VOCAB.fields_by_name['item'].message_type = _VOCAB_ITEM
DESCRIPTOR.message_types_by_name['Vocab'] = _VOCAB

Vocab = _reflection.GeneratedProtocolMessageType('Vocab', (_message.Message,), dict(

  Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
    DESCRIPTOR = _VOCAB_ITEM,
    __module__ = 'vocab_pb2'
    # @@protoc_insertion_point(class_scope:Vocab.Item)
    ))
  ,
  DESCRIPTOR = _VOCAB,
  __module__ = 'vocab_pb2'
  # @@protoc_insertion_point(class_scope:Vocab)
  ))
_sym_db.RegisterMessage(Vocab)
_sym_db.RegisterMessage(Vocab.Item)


# @@protoc_insertion_point(module_scope)
