cc_library(
    name = "ngram_rnn",
    srcs = ["ngram_rnn.cc"],
    hdrs = ["ngram_rnn.h"],
    deps = [
        "//tensorflow/Source/lm:lm",
        "//tensorflow/Source/lm/ngram:ngram",
        "//tensorflow/Source/lm/rnn:rnn_inference",
    ]
)
